server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /api/products {
        proxy_pass http://product-service:5001/api/products;
    }

    location /api/quotes {
        proxy_pass http://quote-service:5002/api/quotes;
    }

    location /api/admin {
        proxy_pass http://admin-service:5003/api/admin;
    }

    location /api/ai {
        proxy_pass http://ai-service:5004/api/ai;
    }

    location / {
        try_files $uri /index.html;
    }
}